# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=1024)),
                ('certificate', models.TextField()),
                ('signing_request', models.TextField()),
                ('key', models.TextField()),
                ('creation_date', models.DateTimeField()),
            ],
        ),
    ]
